pool:
  name: Hosted VS2017
steps:
- script: build.all.bat
  displayName: 'Build Libraries'

- script: |
   chdir /D src\app
   
   .paket\paket.exe restore
   if errorlevel 1 (
     exit /b %errorlevel%
   )
   
   ".paket/paket.exe" install 
   
   chdir /D CalculatorLib.Function
   
   dotnet restore
   dotnet build
  displayName: 'Build Function App'

- script: |
   chdir /D src\app\CalculatorLib.Function
   dotnet publish
  displayName: 'Create Function Publish'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)/src/app/CalculatorLib.Function/bin/Debug/net472/publish'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/app/CalculatorLib.Function/bin/Debug/net472/publish'
    includeRootFolder: false
    archiveFile: '$(Build.StagingDirectory)/$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: CalculatorLib.Function'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: CalculatorLib.Function

