// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("CalculatorLib.Lib.dll")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright © CalculatorLib 2019")]
[assembly: AssemblyCompanyAttribute("CalculatorLib")]
[assembly: AssemblyDescriptionAttribute("Summary")]
[assembly: AssemblyTitleAttribute("CalculatorLib.Lib.dll")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "CalculatorLib.Lib.dll";
        internal const System.String AssemblyVersion = "0.2.0.0";
        internal const System.String AssemblyFileVersion = "0.2.0.0";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyCopyright = "Copyright © CalculatorLib 2019";
        internal const System.String AssemblyCompany = "CalculatorLib";
        internal const System.String AssemblyDescription = "Summary";
        internal const System.String AssemblyTitle = "CalculatorLib.Lib.dll";
    }
}
